name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos:   [windows, linux]
        goarch: [amd64, arm64]
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Build Frontend
      run: |
        cd static
        bun install
        bun run build
        cd ..
        mv static/dist public

    - name: Build ${{ matrix.goos }}_${{ matrix.goarch }}
      id: build
      uses: coalaura/build@v1
      with:
        os: ${{ matrix.goos }}
        arch: ${{ matrix.goarch }}
        cgo: true
        optimization: compatible
        generate: false
        output: build/scratch${{ matrix.goos == 'windows' && '.exe' || '' }}
        go-flags: |
          -trimpath
          -buildvcs=false
          -ldflags=-s -w -X main.Version=${{ github.ref_name }}
          -tags=prod

    - name: Sign ${{ matrix.goos }}_${{ matrix.goarch }}
      id: sign
      uses: coalaura/sign@v1
      with:
        path: ${{ steps.build.outputs.path }}
        key: ${{ secrets.COALAURA_PFX }}
        passphrase: ${{ secrets.COALAURA_PFX_PASSWORD }}
        chain: |
          https://wiese2.org/pki/issuing.pem
          https://wiese2.org/pki/root.pem

    - name: Package signed release
      shell: bash
      run: |
        cp -r public build/public
        tar -czf build/scratch_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz -C build "${{ steps.sign.outputs.filename }}" public

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: scratch_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
        path: build/scratch_${{ github.ref_name }}_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v8
      with:
        pattern: scratch_${{ github.ref_name }}_*.tar.gz
        path: ./build
        merge-multiple: true

    - name: Create GitHub release
      uses: softprops/action-gh-release@v3
      with:
        files: ./build/*.tar.gz
        name: "Release ${{ github.ref_name }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
